yasumi_clock:
  main_window:
    window_pos:
    - 100
    - 100
    - 700
    - 450
    start_draw:
    - 517
    - 282
    - 150
    - 47
    start_fanqie:
    - 517
    - 353
    - 153
    - 47
    animation:
    - 13
    - 15
    - 492
    - 419