yasumi_clock:
  force_rest: true
  LoadingWindow:
    window_pos:
    - 600
    - 282
    - 282
    - 282
    animation:
    - 180
    - 0
    - 282
    - 282
  main_window:
    window_pos:
    - 401
    - 153
    - 546
    - 384
    start_draw:
    - 398
    - 233
    - 128
    - 29
    start_fanqie:
    - 398
    - 339
    - 128
    - 29
    force_rest_checkbox:
    - 398
    - 314
    - 128
    - 17
    animation:
    - 11
    - 5
    - 371
    - 365
    timer:
    - 415
    - 12
    - 111
    - 119
    sub_time:
    - 398
    - 188
    - 34
    - 29
    add_time:
    - 495
    - 188
    - 34
    - 29
    reset_time:
    - 439
    - 188
    - 51
    - 29
    set_time:
    - 435
    - 145
    - 85
    - 34
  history_window:
    window_pos:
    - 470
    - 180
    - 1000
    - 590
    start_draw:
    - 810
    - 550
    - 150
    - 30
    total_time_label:
    - 23
    - 7
    - 750
    - 54
    habbit_label:
    - 23
    - 54
    - 940
    - 120
    week_report_label:
    - 23
    - 168
    - 941
    - 375
    text_label:
    - 23
    - 545
    - 783
    - 37
