yasumi_clock:
  LoadingWindow:
    window_pos:
      - 600
      - 282
      - 282
      - 282
    animation:
      - 180
      - 0 
      - 282
      - 282
  main_window:
    window_pos:
    - 650
    - 282
    - 700
    - 450
    start_draw:
    - 517
    - 282
    - 150
    - 47
    start_fanqie:
    - 517
    - 353
    - 153
    - 47
    animation:
    - 13
    - 15
    - 492
    - 419
    timer:
    - 517
    - 15
    - 151
    - 140