yasumi_clock:
  LoadingWindow:
    window_pos:
      - 600
      - 282
      - 282
      - 282
    animation:
      - 180
      - 0 
      - 282
      - 282
  main_window:
    window_pos:
    - 650
    - 282
    - 700
    - 450
    start_draw:
    - 517
    - 282
    - 150
    - 47
    start_fanqie:
    - 517
    - 353
    - 153
    - 47
    animation:
    - 13
    - 15
    - 492
    - 419
    timer:
    - 537
    - 15
    - 131
    - 140
    sub_time:
    - 517
    - 221
    - 40
    - 34
    add_time:
    - 630
    - 221
    - 40 
    - 34
    reset_time:
    - 565
    - 221
    - 60
    - 34
    set_time:
    - 560
    - 171
    - 100
    - 40

